background = #000000
foreground = #d3f8ff
cursor-color = #effcff
selection-background = #1b4047
selection-foreground = #effcff

palette = 0=#000000
palette = 1=#ff78d5
palette = 2=#61e6ff
palette = 3=#ff91dc
palette = 4=#7debff
palette = 5=#ff9de0
palette = 6=#adf2ff
palette = 7=#d3f8ff
palette = 8=#809ba0
palette = 9=#ffa6e3
palette = 10=#84ecff
palette = 11=#ffbfeb
palette = 12=#b0f2ff
palette = 13=#ffc5ed
palette = 14=#d0f8ff
palette = 15=#effcff
