foreground #d3f8ff
background #000000
selection_foreground #effcff
selection_background #1b4047

cursor #effcff
cursor_text_color #000000

active_border_color #61e6ff
active_tab_background #61e6ff

color0 #000000
color1 #ff78d5
color2 #61e6ff
color3 #ff91dc
color4 #7debff
color5 #ff9de0
color6 #adf2ff
color7 #d3f8ff
color8 #809ba0
color9 #ffa6e3
color10 #84ecff
color11 #ffbfeb
color12 #b0f2ff
color13 #ffc5ed
color14 #d0f8ff
color15 #effcff
