[image-picker]
scrim                   = "#000000"
scrim-alpha             = 0.5
text                    = "#7debff"
selected-border         = "#61e6ff"
selected-border-alpha   = 1.0
unselected-border       = "#d3f8ff"
unselected-border-alpha = 0.28
