background = #000000
foreground = #f7fbff
cursor-color = #fcfeff
selection-background = #404347
selection-foreground = #fcfeff

palette = 0=#000000
palette = 1=#e7f3ff
palette = 2=#e4f1ff
palette = 3=#ecf5ff
palette = 4=#e9f4ff
palette = 5=#eef6ff
palette = 6=#f1f8ff
palette = 7=#f7fbff
palette = 8=#9a9da0
palette = 9=#eff7ff
palette = 10=#eaf4ff
palette = 11=#f4f9ff
palette = 12=#f2f8ff
palette = 13=#f5faff
palette = 14=#f7fbff
palette = 15=#fcfeff
