foreground #f7fbff
background #000000
selection_foreground #fcfeff
selection_background #404347

cursor #fcfeff
cursor_text_color #000000

active_border_color #e4f1ff
active_tab_background #e4f1ff

color0 #000000
color1 #e7f3ff
color2 #e4f1ff
color3 #ecf5ff
color4 #e9f4ff
color5 #eef6ff
color6 #f1f8ff
color7 #f7fbff
color8 #9a9da0
color9 #eff7ff
color10 #eaf4ff
color11 #f4f9ff
color12 #f2f8ff
color13 #f5faff
color14 #f7fbff
color15 #fcfeff
