mode = "dark"

accent = "#ffd166"
selection = "#473b1d"
muted = "#a09781"

background = "#000000"
dark_background = "#000000"
darker_background = "#000000"
lighter_background = "#141414"

foreground = "#fff2d4"
dark_foreground = "#ac9e7e"
light_foreground = "#ffe4a6"
bright_foreground = "#fffaf0"

hyprland_active_border = "#ffd166 #e6a02f 45deg"

red = "#ffd778"
yellow = "#ffde91"
orange = "#ffda85"
green = "#ffd166"
cyan = "#ffe7af"
blue = "#ffd982"
magenta = "#ffe29d"
brown = "#b8aa8a"

bright_red = "#ffe4a6"
bright_yellow = "#ffecbf"
bright_green = "#ffdb88"
bright_cyan = "#fff1d1"
bright_blue = "#ffe8b2"
bright_magenta = "#ffeec5"
