background = #000000
foreground = #fff2d4
cursor-color = #fffaf0
selection-background = #473b1d
selection-foreground = #fffaf0

palette = 0=#000000
palette = 1=#ffd778
palette = 2=#ffd166
palette = 3=#ffde91
palette = 4=#ffd982
palette = 5=#ffe29d
palette = 6=#ffe7af
palette = 7=#fff2d4
palette = 8=#a09781
palette = 9=#ffe4a6
palette = 10=#ffdb88
palette = 11=#ffecbf
palette = 12=#ffe8b2
palette = 13=#ffeec5
palette = 14=#fff1d1
palette = 15=#fffaf0
