foreground #fff2d4
background #000000
selection_foreground #fffaf0
selection_background #473b1d

cursor #fffaf0
cursor_text_color #000000

active_border_color #ffd166
active_tab_background #ffd166

color0 #000000
color1 #ffd778
color2 #ffd166
color3 #ffde91
color4 #ffd982
color5 #ffe29d
color6 #ffe7af
color7 #fff2d4
color8 #a09781
color9 #ffe4a6
color10 #ffdb88
color11 #ffecbf
color12 #ffe8b2
color13 #ffeec5
color14 #fff1d1
color15 #fffaf0
