[controls]

normal-color        = "#ffd982"
normal-fill-alpha   = 0.04
normal-border       = "#fff2d4"
normal-border-width = 1
normal-border-alpha = 0.4

hover-cursor-color        = "#ffd982"
hover-cursor-fill-alpha   = 0.08
hover-cursor-border       = "#fff2d4"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 0.5

focus-color        = "#ffd982"
focus-fill-alpha   = 0.08
focus-border       = "#ffd166"
focus-border-width = 1
focus-border-alpha = 0.65

selected-color        = "#ffd982"
selected-fill-alpha   = 0.18
selected-border       = "#fff2d4"
selected-border-width = 0
selected-border-alpha = 1.0

pressed-fill-alpha   = 0.22
selection-fill-alpha = 0.35
