background = #000000
foreground = #d4e7ff
cursor-color = #f0f6ff
selection-background = #1c3047
selection-foreground = #f0f6ff

palette = 0=#000000
palette = 1=#ffeb6f
palette = 2=#64aaff
palette = 3=#ffee89
palette = 4=#80b9ff
palette = 5=#fff096
palette = 6=#aed3ff
palette = 7=#d4e7ff
palette = 8=#818fa0
palette = 9=#fff2a0
palette = 10=#86bdff
palette = 11=#fff5ba
palette = 12=#b2d4ff
palette = 13=#fff6c1
palette = 14=#d0e5ff
palette = 15=#f0f6ff
