foreground #d4e7ff
background #000000
selection_foreground #f0f6ff
selection_background #1c3047

cursor #f0f6ff
cursor_text_color #000000

active_border_color #64aaff
active_tab_background #64aaff

color0 #000000
color1 #ffeb6f
color2 #64aaff
color3 #ffee89
color4 #80b9ff
color5 #fff096
color6 #aed3ff
color7 #d4e7ff
color8 #818fa0
color9 #fff2a0
color10 #86bdff
color11 #fff5ba
color12 #b2d4ff
color13 #fff6c1
color14 #d0e5ff
color15 #f0f6ff
