background = #000000
foreground = #d2f1ff
cursor-color = #effaff
selection-background = #1b3947
selection-foreground = #effaff

palette = 0=#000000
palette = 1=#73d2ff
palette = 2=#60ccff
palette = 3=#8ddaff
palette = 4=#7dd5ff
palette = 5=#99deff
palette = 6=#ace4ff
palette = 7=#d2f1ff
palette = 8=#8096a0
palette = 9=#a3e1ff
palette = 10=#83d7ff
palette = 11=#bceaff
palette = 12=#b0e6ff
palette = 13=#c3ecff
palette = 14=#cff0ff
palette = 15=#effaff
