foreground #d2f1ff
background #000000
selection_foreground #effaff
selection_background #1b3947

cursor #effaff
cursor_text_color #000000

active_border_color #60ccff
active_tab_background #60ccff

color0 #000000
color1 #73d2ff
color2 #60ccff
color3 #8ddaff
color4 #7dd5ff
color5 #99deff
color6 #ace4ff
color7 #d2f1ff
color8 #8096a0
color9 #a3e1ff
color10 #83d7ff
color11 #bceaff
color12 #b0e6ff
color13 #c3ecff
color14 #cff0ff
color15 #effaff
