[controls]

normal-color        = "#7dd5ff"
normal-fill-alpha   = 0.04
normal-border       = "#d2f1ff"
normal-border-width = 1
normal-border-alpha = 0.4

hover-cursor-color        = "#7dd5ff"
hover-cursor-fill-alpha   = 0.08
hover-cursor-border       = "#d2f1ff"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 0.5

focus-color        = "#7dd5ff"
focus-fill-alpha   = 0.08
focus-border       = "#60ccff"
focus-border-width = 1
focus-border-alpha = 0.65

selected-color        = "#7dd5ff"
selected-fill-alpha   = 0.18
selected-border       = "#d2f1ff"
selected-border-width = 0
selected-border-alpha = 1.0

pressed-fill-alpha   = 0.22
selection-fill-alpha = 0.35
