background = #000000
foreground = #ecddff
cursor-color = #f8f3ff
selection-background = #352647
selection-foreground = #f8f3ff

palette = 0=#000000
palette = 1=#c495ff
palette = 2=#bc86ff
palette = 3=#cfa8ff
palette = 4=#c89cff
palette = 5=#d4b2ff
palette = 6=#dcc0ff
palette = 7=#ecddff
palette = 8=#9288a0
palette = 9=#d8b9ff
palette = 10=#cba1ff
palette = 11=#e3ccff
palette = 12=#dec2ff
palette = 13=#e6d1ff
palette = 14=#ebdbff
palette = 15=#f8f3ff
