foreground #ecddff
background #000000
selection_foreground #f8f3ff
selection_background #352647

cursor #f8f3ff
cursor_text_color #000000

active_border_color #bc86ff
active_tab_background #bc86ff

color0 #000000
color1 #c495ff
color2 #bc86ff
color3 #cfa8ff
color4 #c89cff
color5 #d4b2ff
color6 #dcc0ff
color7 #ecddff
color8 #9288a0
color9 #d8b9ff
color10 #cba1ff
color11 #e3ccff
color12 #dec2ff
color13 #e6d1ff
color14 #ebdbff
color15 #f8f3ff
