background = #000000
foreground = #e9ddff
cursor-color = #f7f3ff
selection-background = #312547
selection-foreground = #f7f3ff

palette = 0=#000000
palette = 1=#ffc874
palette = 2=#b084ff
palette = 3=#ffd28d
palette = 4=#be9aff
palette = 5=#ffd79a
palette = 6=#d6bfff
palette = 7=#e9ddff
palette = 8=#9087a0
palette = 9=#ffdaa3
palette = 10=#c19fff
palette = 11=#ffe5bd
palette = 12=#d8c2ff
palette = 13=#ffe7c3
palette = 14=#e7daff
palette = 15=#f7f3ff
