foreground #e9ddff
background #000000
selection_foreground #f7f3ff
selection_background #312547

cursor #f7f3ff
cursor_text_color #000000

active_border_color #b084ff
active_tab_background #b084ff

color0 #000000
color1 #ffc874
color2 #b084ff
color3 #ffd28d
color4 #be9aff
color5 #ffd79a
color6 #d6bfff
color7 #e9ddff
color8 #9087a0
color9 #ffdaa3
color10 #c19fff
color11 #ffe5bd
color12 #d8c2ff
color13 #ffe7c3
color14 #e7daff
color15 #f7f3ff
