[image-picker]
scrim                   = "#000000"
scrim-alpha             = 0.5
text                    = "#be9aff"
selected-border         = "#b084ff"
selected-border-alpha   = 1.0
unselected-border       = "#e9ddff"
unselected-border-alpha = 0.28
