foreground #ffcdd1
background #000000
selection_foreground #ffedef
selection_background #471619

cursor #ffedef
cursor_text_color #000000

active_border_color #ff4d5b
active_tab_background #ff4d5b

color0 #000000
color1 #ff626f
color2 #ff4d5b
color3 #ff7f89
color4 #ff6d79
color5 #ff8d96
color6 #ffa2aa
color7 #ffcdd1
color8 #a07c7f
color9 #ff98a0
color10 #ff747f
color11 #ffb4ba
color12 #ffa6ad
color13 #ffbbc1
color14 #ffcace
color15 #ffedef
