background = #000000
foreground = #ffe2db
cursor-color = #fff4f2
selection-background = #472a23
selection-foreground = #fff4f2

palette = 0=#000000
palette = 1=#ffa38d
palette = 2=#ff967e
palette = 3=#ffb3a2
palette = 4=#ffa995
palette = 5=#ffbcac
palette = 6=#ffc8bc
palette = 7=#ffe2db
palette = 8=#a08b86
palette = 9=#ffc2b4
palette = 10=#ffad9a
palette = 11=#ffd3c9
palette = 12=#ffcbbe
palette = 13=#ffd7ce
palette = 14=#ffe0d8
palette = 15=#fff4f2
