foreground #ffe2db
background #000000
selection_foreground #fff4f2
selection_background #472a23

cursor #fff4f2
cursor_text_color #000000

active_border_color #ff967e
active_tab_background #ff967e

color0 #000000
color1 #ffa38d
color2 #ff967e
color3 #ffb3a2
color4 #ffa995
color5 #ffbcac
color6 #ffc8bc
color7 #ffe2db
color8 #a08b86
color9 #ffc2b4
color10 #ffad9a
color11 #ffd3c9
color12 #ffcbbe
color13 #ffd7ce
color14 #ffe0d8
color15 #fff4f2
