background = #000000
foreground = #f7e3ff
cursor-color = #fcf5ff
selection-background = #402b47
selection-foreground = #fcf5ff

palette = 0=#000000
palette = 1=#e7a6ff
palette = 2=#e49aff
palette = 3=#ecb6ff
palette = 4=#e9acff
palette = 5=#eebeff
palette = 6=#f1caff
palette = 7=#f7e3ff
palette = 8=#9a8ca0
palette = 9=#efc4ff
palette = 10=#eab0ff
palette = 11=#f4d5ff
palette = 12=#f2ccff
palette = 13=#f5d9ff
palette = 14=#f7e1ff
palette = 15=#fcf5ff
