foreground #f7e3ff
background #000000
selection_foreground #fcf5ff
selection_background #402b47

cursor #fcf5ff
cursor_text_color #000000

active_border_color #e49aff
active_tab_background #e49aff

color0 #000000
color1 #e7a6ff
color2 #e49aff
color3 #ecb6ff
color4 #e9acff
color5 #eebeff
color6 #f1caff
color7 #f7e3ff
color8 #9a8ca0
color9 #efc4ff
color10 #eab0ff
color11 #f4d5ff
color12 #f2ccff
color13 #f5d9ff
color14 #f7e1ff
color15 #fcf5ff
