# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#000000"

# Main text color
theme[main_fg]="#d7ebff"

# Title color for boxes
theme[title]="#d7ebff"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#71b7ff"

# Background color of selected item in processes box
theme[selected_bg]="#203347"

# Foreground color of selected item in processes box
theme[selected_fg]="#71b7ff"

# Color of inactive/disabled text
theme[inactive_fg]="#8391a0"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#add5ff"

# Background color of the percentage meters
theme[meter_bg]="#203347"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#add5ff"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#ffa4b0"
theme[mem_box]="#71b7ff"
theme[net_box]="#ff8293"
theme[proc_box]="#71b7ff"

# Box divider line and small boxes line color
theme[div_line]="#8391a0"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#71b7ff"
theme[temp_mid]="#e8ecf5"
theme[temp_end]="#ff8293"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#b5daff"
theme[cpu_mid]="#8bc4ff"
theme[cpu_end]="#ffa4b0"

# Mem/Disk free meter
theme[free_start]="#ffa4b0"
theme[free_mid]="#8bc4ff"
theme[free_end]="#b5daff"

# Mem/Disk cached meter
theme[cached_start]="#8bc4ff"
theme[cached_mid]="#b5daff"
theme[cached_end]="#ffa4b0"

# Mem/Disk available meter
theme[available_start]="#e8ecf5"
theme[available_mid]="#ff8293"
theme[available_end]="#ff8293"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#71b7ff"
theme[used_mid]="#b5daff"
theme[used_end]="#8bc4ff"

# Download graph colors
theme[download_start]="#e8ecf5"
theme[download_mid]="#ff8293"
theme[download_end]="#ff8293"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#71b7ff"
theme[upload_mid]="#b5daff"
theme[upload_end]="#8bc4ff"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#b5daff"
theme[process_mid]="#8bc4ff"
theme[process_end]="#ffa4b0"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#000000"
theme[gradient_color_1]="#141414"
theme[gradient_color_2]="#203347"
theme[gradient_color_3]="#8391a0"
theme[gradient_color_4]="#8196ac"
theme[gradient_color_5]="#d7ebff"
theme[gradient_color_6]="#add5ff"
theme[gradient_color_7]="#f1f8ff"
