foreground #d7ebff
background #000000
selection_foreground #f1f8ff
selection_background #203347

cursor #f1f8ff
cursor_text_color #000000

active_border_color #71b7ff
active_tab_background #71b7ff

color0 #000000
color1 #ff8293
color2 #71b7ff
color3 #e8ecf5
color4 #8bc4ff
color5 #ffa4b0
color6 #b5daff
color7 #d7ebff
color8 #8391a0
color9 #ffadb8
color10 #90c7ff
color11 #ffffff
color12 #b8dbff
color13 #ffc9d0
color14 #d4e9ff
color15 #f1f8ff
