background = #000000
foreground = #e0ffd7
cursor-color = #f4fff1
selection-background = #29471f
selection-foreground = #f4fff1

palette = 0=#000000
palette = 1=#9eff81
palette = 2=#91ff70
palette = 3=#b0ff98
palette = 4=#a5ff8a
palette = 5=#b9ffa3
palette = 6=#c6ffb5
palette = 7=#e0ffd7
palette = 8=#8aa083
palette = 9=#bfffac
palette = 10=#a9ff8f
palette = 11=#d1ffc3
palette = 12=#c8ffb8
palette = 13=#d5ffc9
palette = 14=#deffd4
palette = 15=#f4fff1
