foreground #e0ffd7
background #000000
selection_foreground #f4fff1
selection_background #29471f

cursor #f4fff1
cursor_text_color #000000

active_border_color #91ff70
active_tab_background #91ff70

color0 #000000
color1 #9eff81
color2 #91ff70
color3 #b0ff98
color4 #a5ff8a
color5 #b9ffa3
color6 #c6ffb5
color7 #e0ffd7
color8 #8aa083
color9 #bfffac
color10 #a9ff8f
color11 #d1ffc3
color12 #c8ffb8
color13 #d5ffc9
color14 #deffd4
color15 #f4fff1
